version: "3"

tasks:
  install:
    deps:
      - build
    cmds:
      - cp dist/embedApp_{{OS}}_{{ARCH}}/embedApp $GOBIN
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --rm-dist
    silent: true
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true